name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run:  |
          cd ./cors-bad
          chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: |
          cd ./cors-bad
          ./gradlew :shadowJar

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build ./cors-bad -f ./cors-bad/Dockerfile --tag ghcr.io/matyrobbrt/file-preview/cors-bad:latest
          docker push ghcr.io/matyrobbrt/file-preview/cors-bad:latest